
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POST = 11;
  public static final int SEMICOLON = 21;
  public static final int RBRACE = 20;
  public static final int TEST = 6;
  public static final int IN = 18;
  public static final int STATUS = 15;
  public static final int EXPECT = 14;
  public static final int IDENTIFIER = 25;
  public static final int ACTIVE = 7;
  public static final int TRUE = 8;
  public static final int LBRACE = 19;
  public static final int PUT = 12;
  public static final int CONTAINS = 17;
  public static final int STRING = 26;
  public static final int EQUALS = 22;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int VERDOTDOT = 24;
  public static final int DOTDOT = 23;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int LET = 5;
  public static final int MULTILINE_STRING = 27;
  public static final int BODY = 16;
  public static final int HEADER = 4;
  public static final int BASE_URL = 3;
  public static final int DELETE = 13;
  public static final int CONFIG = 2;
  public static final int GET = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONFIG",
  "BASE_URL",
  "HEADER",
  "LET",
  "TEST",
  "ACTIVE",
  "TRUE",
  "FALSE",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "EXPECT",
  "STATUS",
  "BODY",
  "CONTAINS",
  "IN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "EQUALS",
  "DOTDOT",
  "VERDOTDOT",
  "IDENTIFIER",
  "STRING",
  "MULTILINE_STRING",
  "NUMBER"
  };
}

